### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by peddamat** [devidw/obsidian-to-hugo#16]
I did a `pip install` in a WSL container.

Trying to import the module from a Python 3 REPL results in:

```
$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from obsidian_to_hugo import ObsidianToHugo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.8/site-packages/obsidian_to_hugo/__init__.py", line 1, in <module>
    from .obsidian_to_hugo import ObsidianToHugo
  File "/home/me/.local/lib/python3.8/site-packages/obsidian_to_hugo/obsidian_to_hugo.py", line 8, in <module>
    from .wiki_links_processor import replace_wiki_links
  File "/home/me/.local/lib/python3.8/site-packages/obsidian_to_hugo/wiki_links_processor.py", line 12, in <module>
    def get_wiki_links(text: str) -> list[WikiLink]:
TypeError: 'type' object is not subscriptable
>>>
```

**Comment by devidw** [comment]
This was fixed in #15 by @green-leader, but not released to PyPI until now.

You should be able to import without errors in the latest version?
